apiVersion: v1
kind: Service
metadata:  
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.9.5
    release: istio
  name: istio-ingressgateway-nodeport
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443   
    - name: tcp-istiod
      port: 15012
      protocol: TCP
      targetPort: 15012 
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021       
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443        
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
