apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: chip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chip
  name: chip
  namespace: chip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chip
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: chip
        name: chip
    spec:
      containers:
      - image: fidelissauro/chip:v1
        livenessProbe:
          failureThreshold: 2
          httpGet:
            httpHeaders:
            - name: Custom-Header
              value: Awesome
            path: /healthcheck
            port: 8080
          periodSeconds: 10
        name: chip
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 256m
            memory: 512m
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /healthcheck
            port: 8080
          periodSeconds: 10
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: chip
  namespace: chip
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chip
  namespace: chip
spec:
  rules:
  - host: chip.local.cluster
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: chip
            port:
              number: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: chip
  namespace: chip
spec:
  maxReplicas: 10
  minReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chip
---