---
apiVersion: v1
kind: Namespace
metadata:
  name: chip
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: chip
  namespace: chip
  labels:
    app: chip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chip
  template:
    metadata:
      labels:
        app: chip
        name: chip
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: fidelissauro/chip:v1
        name: chip
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "256m"
            memory: "512m"
---
kind: Service
apiVersion: v1
metadata:
  name: chip
  namespace: chip
spec:
  selector:
    app: chip
  ports:
    - protocol: TCP
      port: 8080
      name: web
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chip
  namespace: chip
spec:
  rules:
  - host: chip.raj.ninja
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: chip
            port:
              number: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: chip
  namespace: chip
spec:
  maxReplicas: 5
  minReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chip