apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: default
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: grafana.local.cluster
      http:
        paths:
          - backend:
              serviceName: prometheus-grafana
              servicePort: 80