---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: prometheus
spec:
  ingressClassName: cilium
  rules:
  - host: prometheus.k8s.cluster.local
    http:
      paths:
      - backend:
          service:
            name: prometheus-prometheus
            port:
              number: 9090
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alartmanager-ingress
  namespace: prometheus
spec:
  ingressClassName: cilium
  rules:
  - host: alertmanager.k8s.cluster.local
    http:
      paths:
      - backend:
          service:
            name: prometheus-alertmanager
            port:
              number: 9093
        path: /
        pathType: Prefix